spring.application.name=spring-items-service
spring.datasource.url=jdbc:h2:mem:items;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
